### PR TITLE
Functions to facilitate VCF comparison using sgkit

### PR DESCRIPTION
**Pull request by szhan**
Addresses #94

### CODE REVIEW

**Review by benjeffery — COMMENTED** [review]
Nice!
Great that we have this working for small datasets, but this isn't going to scale as all the genotypes are bought into RAM as your return type is a list of lists.

For this to work on large datasets, I think you'll need to return copies of ds1 and ds2, where they are filtered down to the common sites and ds2 is remapped. Does that make sense for what you are trying to do? 

Lets talk Monday in the office about how we can modify this code to achieve that.

**Comment by szhan** [comment]
Thanks, @benjeffery !

Just to get an idea of next steps. The function should return `xarray.DataArray`, right? So that `zarr` can act upon it. Or I just use some existing functions in `sgkit` to do this?

**Comment by szhan** [comment]
Should we just do that all within `remap_genotypes`? Or is that too much going on for a single function?

**Comment by szhan** [comment]
Since `sgkit` `xarray` datasets have the variable `variant_contig`, the function should check both `variant_contig` and `variant_positions`.

**Comment by szhan** [comment]
I'm thinking that `get_matching_indices` should return `xarray.DataArray` as well. It should help analyse big data sets, right? @benjeffery

**Comment by szhan** [comment]
I've modified `get_matching_indices` to return `numpy.ndarray` instead of `list`.

**Comment by szhan** [comment]
The "compatible" `ds1` and `ds2` should have the same allele lists.

**Comment by szhan** [comment]
What i'd like to do is multi-way VCF comparisons, i.e., imputed genotypes from lshmm (`ds_lshmm`), imputed genotypes from BEAGLE (`ds_beagle`), and ground-truth genotypes (`ds_truth`). I think the easiest way is to just make `ds_lshmm` and `ds_beagle` compatible with `ds_truth` by calling `make_compatible_genotypes` twice.

**Comment by szhan** [comment]
For now, let's assume that only ACGT are allowed, to keep things simple.

**Comment by szhan** [comment]
Also, I still need to add tests for `make_compatible_genotypes`.

**Comment by szhan** [comment]
There are still more tests that could be added, but the current tests are good enough, I think. Will continue adding more tests in a separate issue.

**Pull request merged**
